export const EVENT_CATEGORY = [
  { value: 'children_family', label: 'Children, Family' },
  { value: 'business', label: 'Business' },
  { value: 'design_photo_video', label: 'Design, Photo, Video' },
  { value: 'fashion_beauty', label: 'Fashion, Beauty' },
  { value: 'film_cinema', label: 'Film, Cinema' },
  { value: 'game_esports', label: 'Game, E-Sports' },
  { value: 'hobby_crafts', label: 'Hobby, Crafts' },
  { value: 'investment_stocks', label: 'Investment, Stocks' },
  { value: 'career_self_development', label: 'Career, Self Development' },
  { value: 'religion', label: 'Religion' },
  { value: 'health_fitness', label: 'Health, Fitness' },
  { value: 'finance', label: 'Finance' },
  { value: 'environment', label: 'Environment' },
  { value: 'food_drinks', label: 'Food, Drinks' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'music', label: 'Music' },
  { value: 'sports', label: 'Sports' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'science_technology', label: 'Science, Technology' },
  { value: 'arts_culture', label: 'Arts, Culture' },
  { value: 'social_law_politics', label: 'Social, Law, Politics' },
  { value: 'standup_comedy', label: 'Standup Comedy' },
  { value: 'education_scholarships', label: 'Education, Scholarships' },
  { value: 'tech_startup', label: 'Tech, Start-Up' },
  { value: 'travel_holidays', label: 'Travel & Holidays' },
  { value: 'others', label: 'Others' },
];
