[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash - && pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run serve"