[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["apt install wget && wget -qO- https://get.pnpm.io/install.sh | sh - && pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run serve"