[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "apt-get update -y && apt-get install -y wget curl",
  "curl -fsSL https://get.pnpm.io/install.sh | sh -",
  "export PATH=$HOME/.local/share/pnpm:$PATH && pnpm install"
]

[phases.build]
cmds = ["export PATH=$HOME/.local/share/pnpm:$PATH && pnpm run build"]

[start]
cmd = "export PATH=$HOME/.local/share/pnpm:$PATH && pnpm run serve"
