export const EVENT_CATEGORY_MAP = {
  children_family: 'Children, Family',
  business: 'Business',
  design_photo_video: 'Design, Photo, Video',
  fashion_beauty: 'Fashion, Beauty',
  film_cinema: 'Film, Cinema',
  game_esports: 'Game, E-Sports',
  hobby_crafts: 'Hobby, Crafts',
  investment_stocks: 'Investment, Stocks',
  career_self_development: 'Career, Self Development',
  religion: 'Religion',
  health_fitness: 'Health, Fitness',
  finance: 'Finance',
  environment: 'Environment',
  food_drinks: 'Food, Drinks',
  marketing: 'Marketing',
  music: 'Music',
  sports: 'Sports',
  automotive: 'Automotive',
  science_technology: 'Science, Technology',
  arts_culture: 'Arts, Culture',
  social_law_politics: 'Social, Law, Politics',
  standup_comedy: 'Standup Comedy',
  education_scholarships: 'Education, Scholarships',
  tech_startup: 'Tech, Start-Up',
  travel_holidays: 'Travel & Holidays',
  others: 'Others',
};
